# Generated by Django 3.2.16 on 2023-02-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_auto_20230222_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Только slug-значения, максимум 200 символов',
                max_length=200,
                unique=True,
                verbose_name='slug',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                default=1,
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='catalog_items',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                default=1,
                related_name='catalog_items',
                to='catalog.Tag',
                verbose_name='тег',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Только slug-значения, максимум 200 символов',
                max_length=200,
                unique=True,
                verbose_name='slug',
            ),
        ),
    ]
