# Generated by Django 3.2.16 on 2023-02-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_auto_20230222_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='catalog_items',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                related_name='catalog_items',
                to='catalog.Tag',
                verbose_name='тег',
            ),
        ),
    ]
