# Generated by Django 3.2.16 on 2023-02-22 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0005_auto_20230222_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
