# Generated by Django 3.2.16 on 2023-02-22 15:08

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0010_auto_20230222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text='Максимум 32767',
                validators=[catalog.models.weight_validator],
                verbose_name='вес',
            ),
        ),
    ]
