# Generated by Django 3.2.16 on 2023-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='название'),
        ),
    ]
