# Generated by Django 3.2.16 on 2023-02-22 18:36

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0013_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                default='роскошно',
                help_text="Описание должно содержать слова 'роскошно' и 'превосходно'",
                validators=[
                    catalog.validators.ValidateMustContain(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='описание',
            ),
        ),
    ]
