# Generated by Django 3.2.16 on 2023-03-01 16:09

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0015_gallery_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(
                default='роскошно',
                help_text="Описание должно содержать слова 'роскошно' и 'превосходно'",
                validators=[
                    catalog.validators.ValidateMustContain(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='описание',
            ),
        ),
    ]
