# Generated by Django 3.2.16 on 2023-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status_processing',
            field=models.TextField(
                choices=[
                    (0, 'получено'),
                    (1, 'в обработке'),
                    (2, 'ответ дан'),
                ],
                default='получено',
                verbose_name='статус обработки',
            ),
        ),
    ]
